# programming language
language: node_js
node_js:
  - "node"

# cache dependencies
cache:
  directories:
    - ./client/node_modules
    - ./server/node_modules

# log some version information
before_install:
  - node --version
  - npm --version
  - ls -la

# install dependencies
install:
  - cd client
  - npm i
  - cd ../server
  - npm i

# log some version information
before_script:
  - node --version
  - npm --version
  - ls -la

# build the pwa
script:
  - cd ../client
  - npm run build --prod
  - cd ../server
  - npm run test