# programming language
language: node_js
node_js:
  - "node"

# cache dependencies
cache:
  directories:
    - ./client/node_modules
    - ./server/node_modules

# log some version information
before_install:
  - node --version
  - npm --version

# install dependencies
install:
  - cd client
  - ls -la
  - npm i
  
  - cd ..
  - ls -la

  - cd server
  - ls -la
  - npm i

# log some version information
before_script:
  - node --version
  - npm --version
  - ls -la

# build the pwa
script:
  - cd ..
  - ls -la

  - cd client
  - ls -la
  - npm run build --prod

  - cd ..
  - ls -la

  - cd server
  - ls -la
  - npm run test